apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kastlewatch.fullname" . }}-config
  labels:
    {{- include "kastlewatch.labels" . | nindent 4 }}
data:
  config.toml: |
    [controller]
    base_url = "http://{{ include "kastlewatch.fullname" . }}-worker:{{ .Values.worker.service.port }}"
    
    [worker]
    host = "{{ .Values.config.worker.host }}"
    port = {{ .Values.config.worker.port }}
