apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kastlewatch.fullname" . }}-controller
  labels:
    {{- include "kastlewatch.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    matchLabels:
      {{- include "kastlewatch.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        {{- include "kastlewatch.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: controller
    spec:
      serviceAccountName: {{ include "kastlewatch.serviceAccountName" . }}
      containers:
        - name: controller
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/kastlewatch", "controller"]
          workingDir: /config
          volumeMounts:
            - name: config
              mountPath: /config
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "kastlewatch.fullname" . }}-config
