apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kastlewatch.fullname" . }}
  labels:
    {{- include "kastlewatch.labels" . | nindent 4 }}
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["kastlewatch.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kastlewatch.fullname" . }}
  labels:
    {{- include "kastlewatch.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kastlewatch.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kastlewatch.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
